# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'linux'
    static_configs:
    - targets: ['192.168.180.191:9100', '192.168.180.192:9100', '192.168.180.193:9100', '192.168.180.194:9100', '192.168.180.195:9100', '192.168.180.196:9100', '192.168.180.197:9100', '192.168.180.198:9100', '192.168.180.199:9100']

  - job_name: 'windows'
    static_configs:
    - targets: ['192.168.180.188:9182', '192.168.180.189:9182', '192.168.180.206:9182']

  - job_name: 'jmx'
    static_configs:
    - targets: ['192.168.180.198:9404', '192.168.180.199:9404', '192.168.180.100:9404']

  - job_name: 'oracledb'
    static_configs:
    - targets: ['192.168.180.206:9161']

  - job_name: 'mysqldb'
    static_configs:
    - targets: ['192.168.180.179:9104','192.168.180.195:9104']

  - job_name: 'consul'
    static_configs:
    - targets: ['192.168.180.182:9107', '192.168.180.183:9107', '192.168.180.184:9107']

  - job_name: 'haproxy'
    static_configs:
    - targets: ['192.168.180.191:9101', '192.168.180.192:9101']
